services:
  app:
    build: .
    container_name: index
    ports:
      - "8000:8000"
    restart: unless-stopped
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - dhis_network
    volumes:
      - dhis_app_storage:/var/www/storage

  redis:
    image: redis:7-alpine
    container_name: dhis_redis
    restart: unless-stopped
    networks:
      - dhis_network
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 5s
      retries: 5

networks:
  dhis_network:
    driver: bridge

volumes:
  dhis_app_storage:
