services:
  app:
    build: .
    container_name: dhisproject_vue
    ports:
      - "8000:80"
    restart: unless-stopped
    networks:
      - dhis_network

networks:
  dhis_network:
    driver: bridge
